from typing import TypedDict, List, Optional, Dict, Any


class QuizQuestion(TypedDict):
    type: str                       # "mcq" | "code" | "text"
    question: str
    options: Optional[List[str]]    # only for mcq, null for code/text
    correct_answer: Optional[str]   # null for text (reflection) questions
    student_answer: Optional[str]   # filled after student submits


class QuizResult(TypedDict):
    week: Optional[int]             # set for task quizzes; null for prereq quizzes
    concept: str
    questions: List[QuizQuestion]
    passed: bool
    score: int                      # auto-graded questions only


class Prerequisite(TypedDict):
    concept: str
    explanation: str
    toy_task: str
    estimated_time: str             # always "1 day"


class AgentState(TypedDict):
    # ── identity ──────────────────────────────────────────────────────────────
    user_id: str

    # ── project setup ─────────────────────────────────────────────────────────
    project: Dict[str, Any]         # {name, description}
    known_stack: List[str]
    unknown_stack: List[str]

    # ── github ────────────────────────────────────────────────────────────────
    repo_url: Optional[str]         # "https://github.com/owner/repo"
    github_branch: Optional[str]    # default "main"

    # ── prerequisite phase ────────────────────────────────────────────────────
    prerequisites: List[Prerequisite]       # generated by PrerequisiteNode
    current_concept_index: int              # loop pointer (0-indexed)
    quiz_results: List[QuizResult]          # one entry per prereq concept

    # ── planning phase ────────────────────────────────────────────────────────
    student_approach: Optional[str]         # free-text from student
    analysis: Optional[Dict[str, Any]]      # positives, gaps, focus_areas
    roadmap: Optional[Dict[str, Any]]       # full week-by-week roadmap

    # ── weekly execution phase ────────────────────────────────────────────────
    weekly_tasks: Optional[List[Dict[str, Any]]]    # 5 daily tasks for current week
    current_week: int                               # 1-indexed week counter
    completion_status: Optional[bool]               # True = done, False = not done
    completion_reason: Optional[str]                # human-readable from CompletionCheckNode
    task_quiz_results: Optional[List[QuizResult]]   # one entry per week
    weekly_score: Optional[float]                   # -5 to +5 from EvaluatorNode
    weekly_score_display: Optional[float]           # 0 to 10 (mapped for UI)
    evaluation_feedback: Optional[Dict[str, Any]]   # strength, improvement, message, tip
    project_complete: bool                          # True when final week evaluated

    # ── timeline ──────────────────────────────────────────────────────────────
    start_date: Optional[str]               # "YYYY-MM-DD"
    end_date: Optional[str]                 # "YYYY-MM-DD"
    blackout_dates: Optional[List[str]]     # list of "YYYY-MM-DD" strings